In [36]:
###Import all the required libraries
import pandas as pd
from pandas import json_normalize
import json
from datetime import datetime

# Replace 'your_file.json' with the actual path to your JSON file
json_file_path = 'C:/Users/princ/PycharmProjects/pythonProject/Assessment/receipts.json'

# Read JSON file line by line into a list
with open(json_file_path, 'r') as file:
    lines = file.readlines()

data = [json.loads(line) for line in lines] # Load each line as a separate JSON object
# Use json_normalize to flatten the nested structure
receipts = json_normalize(data)
receipts.head(10)

,bonusPointsEarned,bonusPointsEarnedReason,pointsEarned,purchasedItemCount,rewardsReceiptItemList,rewardsReceiptStatus,totalSpent,userId,_id.$oid,createDate.$date,dateScanned.$date,finishedDate.$date,modifyDate.$date,pointsAwardedDate.$date,purchaseDate.$date
0,500.0,"Receipt number 2 completed, bonus point schedu...",500.0,5.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,26.00,5ff1e1eacfcf6c399c274ae6,5ff1e1eb0a720f0523000575,1609687531000,1609687531000,1.609688e+12,1609687536000,1.609688e+12,1.609632e+12
1,150.0,"Receipt number 5 completed, bonus point schedu...",150.0,2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,11.00,5ff1e194b6a9d73a3a9f1052,5ff1e1bb0a720f052300056b,1609687483000,1609687483000,1.609687e+12,1609687488000,1.609687e+12,1.609601e+12
2,5.0,All-receipts receipt bonus,5,1.0,"[{'needsFetchReview': False, 'partnerItemId': ...",REJECTED,10.00,5ff1e1f1cfcf6c399c274b0b,5ff1e1f10a720f052300057a,1609687537000,1609687537000,NaN,1609687542000,NaN,1.609632e+12
3,5.0,All-receipts receipt bonus,5.0,4.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,28.00,5ff1e1eacfcf6c399c274ae6,5ff1e1ee0a7214ada100056f,1609687534000,1609687534000,1.609688e+12,1609687539000,1.609688e+12,1.609632e+12
4,5.0,All-receipts receipt bonus,5.0,2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.00,5ff1e194b6a9d73a3a9f1052,5ff1e1d20a7214ada1000561,1609687506000,1609687506000,1.609688e+12,1609687511000,1.609688e+12,1.609601e+12
5,750.0,"Receipt number 1 completed, bonus point schedu...",750.0,1.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,3.25,5ff1e1e4cfcf6c399c274ac3,5ff1e1e40a7214ada1000566,1609687524000,1609687524000,1.609688e+12,1609687530000,1.609688e+12,1.609601e+12
6,5.0,All-receipts receipt bonus,5.0,1.0,"[{'brandCode': 'MISSION', 'competitorRewardsGr...",FINISHED,2.23,5ff1e194b6a9d73a3a9f1052,5ff1e1cd0a720f052300056f,1609687501000,1609687501000,1.609688e+12,1609687502000,1.609688e+12,1.609688e+12
7,500.0,"Receipt number 2 completed, bonus point schedu...",500.0,1.0,"[{'barcode': '046000832517', 'brandCode': 'BRA...",FINISHED,10.00,5ff1e194b6a9d73a3a9f1052,5ff1e1a40a720f0523000569,1609687460000,1609687460000,1.609687e+12,1609687461000,1.609687e+12,1.609027e+12
8,5.0,All-receipts receipt bonus,5.0,5.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,20.00,5ff1e1eacfcf6c399c274ae6,5ff1e1ed0a7214ada100056e,1609687533000,1609687533000,1.609688e+12,1609687538000,1.609688e+12,1.609632e+12
9,250.0,"Receipt number 3 completed, bonus point schedu...",250.0,3.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,20.00,5ff1e1eacfcf6c399c274ae6,5ff1e1eb0a7214ada100056b,1609687531000,1609687531000,1.609688e+12,1609687536000,1.609688e+12,1.609632e+12

In [37]:
receipts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1119 entries, 0 to 1118
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   bonusPointsEarned        544 non-null    float64
 1   bonusPointsEarnedReason  544 non-null    object
 2   pointsEarned             609 non-null    object
 3   purchasedItemCount       635 non-null    float64
 4   rewardsReceiptItemList   679 non-null    object
 5   rewardsReceiptStatus     1119 non-null   object
 6   totalSpent               684 non-null    object
 7   userId                   1119 non-null   object
 8   _id.$oid                 1119 non-null   object
 9   createDate.$date         1119 non-null   int64
 10  dateScanned.$date        1119 non-null   int64
 11  finishedDate.$date       568 non-null    float64
 12  modifyDate.$date         1119 non-null   int64
 13  pointsAwardedDate.$date  537 non-null    float64
 14  purchaseDate.$date       671 non-null    float64
dtypes: float64(5), int64(3), object(7)
memory usage: 131.3+ KB

In [38]:
receipts.rename(columns={
    '_id.$oid': 'receipt_id',
    'createDate.$date':'created_date',
    'dateScanned.$date':'date_scanned',
    'finishedDate.$date':'finished_date',
    'modifyDate.$date':'modify_date',
    'pointsAwardedDate.$date':'pointsAwarded_date',
    'purchaseDate.$date':'purchase_date'}, inplace=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1119 entries, 0 to 1118
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   bonusPointsEarned        544 non-null    float64
 1   bonusPointsEarnedReason  544 non-null    object
 2   pointsEarned             609 non-null    object
 3   purchasedItemCount       635 non-null    float64
 4   rewardsReceiptItemList   679 non-null    object
 5   rewardsReceiptStatus     1119 non-null   object
 6   totalSpent               684 non-null    object
 7   userId                   1119 non-null   object
 8   receipt_id               1119 non-null   object
 9   created_date             1119 non-null   int64
 10  date_scanned             1119 non-null   int64
 11  finished_date            568 non-null    float64
 12  modify_date              1119 non-null   int64
 13  pointsAwarded_date       537 non-null    float64
 14  purchase_date            671 non-null    float64
dtypes: float64(5), int64(3), object(7)
memory usage: 131.3+ KB

In [39]:
date_columns = ['created_date', 'date_scanned', 'finished_date', 'modify_date', 'pointsAwarded_date', 'purchase_date']
for col in date_columns:
    # Applying the conversion only to non-null values to avoid errors
    # Convert milliseconds to seconds and then to datetime
    receipts[col] = receipts[col].dropna().apply(lambda x: datetime.fromtimestamp(x / 1000.0))

In [40]:
receipts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1119 entries, 0 to 1118
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   bonusPointsEarned        544 non-null    float64
 1   bonusPointsEarnedReason  544 non-null    object
 2   pointsEarned             609 non-null    object
 3   purchasedItemCount       635 non-null    float64
 4   rewardsReceiptItemList   679 non-null    object
 5   rewardsReceiptStatus     1119 non-null   object
 6   totalSpent               684 non-null    object
 7   userId                   1119 non-null   object
 8   receipt_id               1119 non-null   object
 9   created_date             1119 non-null   datetime64[ns]
 10  date_scanned             1119 non-null   datetime64[ns]
 11  finished_date            568 non-null    datetime64[ns]
 12  modify_date              1119 non-null   datetime64[ns]
 13  pointsAwarded_date       537 non-null    datetime64[ns]
 14  purchase_date            671 non-null    datetime64[ns]
dtypes: datetime64[ns](6), float64(2), object(7)
memory usage: 131.3+ KB

In [41]:
excel_file_path = 'C:/Users/princ/PycharmProjects/pythonProject/Assessment/receipts.xlsx'
receipts.to_excel(excel_file_path, index=False)

In [58]:
receipts.isna().sum()
percentage_null_values= receipts.isnull().mean()
print("Percentage of null values:")
for key, value in percentage_null_values.items():
  if value>0:
    print(f"{key}: {round(value * 100, 2)}%")

Percentage of null values:
bonusPointsEarned: 51.39%
bonusPointsEarnedReason: 51.39%
pointsEarned: 45.58%
purchasedItemCount: 43.25%
rewardsReceiptItemList: 39.32%
totalSpent: 38.87%
finished_date: 49.24%
pointsAwarded_date: 52.01%
purchase_date: 40.04%

The presence of a significant percentage of null values in key fields such as finishedDate, purchaseDate, totalSpent, and purchasedItemCount raises several concerns regarding the consistency and completeness of the dataset.

Missing values for certain variables are a major concern: finishedDate- for 49%(almost half) of the receipts we don't know when do they become invalid(assuming that the date on which a receipt finishes processing is the date on which it becomes invalid)

The absence of purchaseDate in over 40% of the entries make any analysis complex based on the actual purchase behavior over time. This data is crucial for understanding customer purchasing patterns.

Missing data on how much was spent (totalSpent) in nearly 39% of receipts significantly affects financial analysis, such as calculating the average spend per receipt or per user, which is essential for understanding consumer spending behavior.

In [ ]:
"""Checking duplicates"""
duplicates = receipts[receipts.duplicated()]
if not duplicates.empty:
    print('Duplicate rows (except for their first occurrence):')
    print(duplicates)
else:
    print('No duplicate rows found.')

In [55]:
receipts.isna().sum()

bonusPointsEarned          575
bonusPointsEarnedReason    575
pointsEarned               510
purchasedItemCount         484
rewardsReceiptItemList     440
rewardsReceiptStatus         0
totalSpent                 435
userId                       0
receipt_id                   0
created_date                 0
date_scanned                 0
finished_date              551
modify_date                  0
pointsAwarded_date         582
purchase_date              448
dtype: int64

Null values in columns like 'bonusPointsEarned', 'bonusPointsEarnedReason', 'pointsEarned', 'purchasedItemCount', and 'totalSpent' can significantly impact analyses related to customer loyalty, purchasing behavior, and overall engagement. 

Need to investigate on the discrepancies between many related fields such as pointsEarned, bonusPointsEarned, pointsAwarded_date to ensure data consistency and accurate reward point attribution.

In [56]:
print(receipts["pointsEarned"].value_counts())

120
pointsEarned
5.0       152
25.0       63
750.0      49
250.0      37
50.0       27
         ...
2416.7      1
605.7       1
855.7       1
160.0       1
3500.0      1
Name: count, Length: 120, dtype: int64

If we look at the unique values for'pointsEarned', we do not have a zero value. This means that points were earned for certain receipts but the data
was not captured and that's why the large number of missing values.
The purchasedItemCount column contains a large number of missing values, presenting challenges in determining eligibility for special offers or bonus points that necessitate the purchase of specific quantities of products or brands.
totalSpent, rewardsReceiptItemList- Since data for these two fields is missing, it is natural that we don't have
information about points earned (pointsEarned field) for those transactions.